project_id = "kgffwhyfgkqeevsuhldt"

[functions.fetch-prices]
verify_jwt = false

[functions.iyzico-init-3ds]
verify_jwt = false

[functions.iyzico-callback]
verify_jwt = false

[functions.messaging]
verify_jwt = true

[functions.sync-pricecharting-listings]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.generate-item-image]
verify_jwt = false
