project_id = "kgffwhyfgkqeevsuhldt"

[functions.fetch-prices]
verify_jwt = false

[functions.iyzico-init-3ds]
verify_jwt = false

[functions.iyzico-callback]
verify_jwt = false

[functions.messaging]
verify_jwt = true

[functions.sync-pricecharting-listings]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false

[functions.process-referral]
verify_jwt = false

[functions.process-referral-reward]
verify_jwt = false

[functions.generate-item-image]
verify_jwt = false

[functions.fetch-ebay-sales]
verify_jwt = false

[functions.market-insights]
verify_jwt = false

[functions.geliver-shipping]
verify_jwt = false

[functions.scan-card]
verify_jwt = false

[functions.populate-ebay-products]
verify_jwt = false

[functions.ebay-oauth]
verify_jwt = false

[functions.sync-tcgdex-images]
verify_jwt = false

[functions.sync-apitcg-images]
verify_jwt = false

[functions.sync-justtcg-prices]
verify_jwt = false

[functions.import-pricecharting-csv]
verify_jwt = false

[functions.sync-scryfall-images]
verify_jwt = false

[functions.sync-ygopro-images]
verify_jwt = false

[functions.sync-pokemon-images]
verify_jwt = false

[functions.sync-cardmarket-images]
verify_jwt = false
